# ML-05 — Feature Vector and Leakage/Privacy Check

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mennahamdy0/flyrank-machine-learning/blob/main/work/notebooks/w03_feature_leakage_check.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

# Build the Feature Vector

The feature vector contains only variables that are available before making a recommendation.

I selected features that describe search visibility and user engagement without using any future information or label-derived fields.

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    split="train[:5000]"
)

df = dataset.to_pandas()

print(df.shape)
df.head()

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

(5000, 30)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,...,0,0,0,0,0,0,0,0,0,0

In [3]:
import numpy as np

feature_df = df.copy()

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd
import numpy as np

feature_df = df.copy()

# CTR
feature_df["ctr"] = np.where(
    feature_df["gsc_impressions"] > 0,
    feature_df["gsc_clicks"] / feature_df["gsc_impressions"],
    0
)

# Engagement Rate
feature_df["engagement_rate"] = np.where(
    feature_df["ga4_sessions"] > 0,
    feature_df["ga4_engaged_sessions"] / feature_df["ga4_sessions"],
    0
)

# Organic Traffic Ratio
feature_df["organic_ratio"] = np.where(
    feature_df["ga4_sessions"] > 0,
    feature_df["sessions_organic"] / feature_df["ga4_sessions"],
    0
)

# Final Feature Vector
X = feature_df[[
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "ctr",
    "engagement_rate"
]]

X = X.fillna(0)

print("Feature Vector Shape:", X.shape)
display(X.head())

Feature Vector Shape: (5000, 5)

   gsc_impressions  gsc_clicks  gsc_avg_position  ctr  engagement_rate
0               30           0          3.833333  0.0              0.0
1                5           0         71.600000  0.0              0.0
2                1           0         34.000000  0.0              0.0
3                6           0         23.333333  0.0              0.0
4                5           0         17.800000  0.0              0.0

## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

# Feature Notes

| Feature | Meaning | Missing Handling | Available Before Prediction? |
|----------|---------|-----------------|------------------------------|
| gsc_impressions | Number of Google Search impressions | Missing values filled with 0 | Yes |
| gsc_clicks | Number of Google Search clicks | Filled with 0 | Yes |
| gsc_avg_position | Average Google ranking position | Filled with 0 | Yes |
| ctr | Click-through rate | Calculated safely (0 if impressions = 0) | Yes |
| engagement_rate | Percentage of engaged sessions | Calculated safely (0 if sessions = 0) | Yes |

In [5]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
X.info()

print("\nMissing values")
print(X.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gsc_impressions   5000 non-null   int64
 1   gsc_clicks        5000 non-null   int64
 2   gsc_avg_position  5000 non-null   float64
 3   ctr               5000 non-null   float64
 4   engagement_rate   5000 non-null   float64
dtypes: float64(3), int64(2)
memory usage: 195.4 KB

Missing values
gsc_impressions     0
gsc_clicks          0
gsc_avg_position    0
ctr                 0
engagement_rate     0
dtype: int64

## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

# Leakage Hunt

I intentionally tested one feature that should not be used.

Using future or label-derived information can artificially improve model performance.

Only features known before the prediction moment should remain in the final model.

In [6]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

feature_df["fake_label"] = (
    feature_df["gsc_clicks"] > feature_df["gsc_clicks"].median()
).astype(int)

X_leak = X.copy()
X_leak["fake_label"] = feature_df["fake_label"]

y = feature_df["fake_label"]

tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_leak, y)

pred = tree.predict(X_leak)

print("Accuracy with leakage:",
      accuracy_score(y, pred))

Accuracy with leakage: 1.0

In [7]:
X_leak = X.copy()

print("Leakage feature removed.")

Leakage feature removed.

## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

# Excluded Features

| Feature | Why Excluded |
|----------|--------------|
| client_hash_id | Identifier only; no predictive value. |
| content_hash_id | Identifier only. |
| report_date | Used only for filtering, not prediction. |
| gsc_sum_position | Redundant because average position is already used. |
| ai_chatgpt | Not consistently available across all content. |
| ai_claude | Same reason. |
| ai_gemini | Same reason. |
| ai_meta | Sparse feature. |
| ai_other | Sparse feature. |

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
excluded = [
    "client_hash_id",
    "content_hash_id",
    "report_date",
    "gsc_sum_position",
    "ai_chatgpt",
    "ai_claude",
    "ai_gemini",
    "ai_meta",
    "ai_other"
]

print("Excluded Features:")
for f in excluded:
    print("-", f)

Excluded Features:
- client_hash_id
- content_hash_id
- report_date
- gsc_sum_position
- ai_chatgpt
- ai_claude
- ai_gemini
- ai_meta
- ai_other

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

- [x] Every section above is filled.
- [x] The notebook runs from top to bottom.
- [x] No client names or URLs are included.
- [x] Claims use careful language (observed, measured, directional).
- [x] Notebook committed under work/notebooks/.